Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network :forwarded_port, guest: 80, host: 80, host_ip: "localhost"
  config.vm.provision "shell", inline: <<-SCRIPT
    DOCKER_TMP_DIR=/tmp/get-docker.sh

    apt-get update

    apt-get purge -y docker-ce docker-ce-cli containerd.io docker-ce-rootless-extras docker-scan-plugin
    rm -rf /var/lib/docker /var/lib/containerd /etc/docker/ /var/run/docker*
    curl -fsSL https://get.docker.com -o $DOCKER_TMP_DIR
    sh $DOCKER_TMP_DIR || sh $DOCKER_TMP_DIR
    rm -f $DOCKER_TMP_DIR

    BD_CONTAINER_ID=$(docker run -d --name db -e POSTGRES_PASSWORD=secret      -p 5432:5432 postgres)
    BD_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $BD_CONTAINER_ID)

    API_CONTAINER_ID=$(docker run -d --name backend     -e DATABASE_HOST_IP=$BD_IP  -p 8080:8080 sebmoreno/gildedrose-backend)
    API_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $API_CONTAINER_ID)

    docker run -d --name frontend    -e API_HOST_URL=$API_IP -e API_HOST_PORT=8080 -p 80:80     sebmoreno/gildedrose-frontend
  SCRIPT
end